/**
 * GraphDisplay Component
 *
 * Displays mathematical function graphs from base64-encoded PNG images
 *
 * Features:
 * - Base64 PNG image rendering
 * - Responsive sizing (fits screen width)
 * - Maintains aspect ratio
 * - Loading state with spinner
 * - Error state with helpful message
 * - Optional title display
 * - Accessibility support
 * - Alexandria theme styling
 *
 * @example
 * // Basic usage
 * <GraphDisplay imageBase64={graphData.image_base64} />
 *
 * // With title
 * <GraphDisplay
 *   imageBase64={graphData.image_base64}
 *   title="Graph of f(x) = x² - 2x + 1"
 * />
 *
 * // Custom size
 * <GraphDisplay
 *   imageBase64={graphData.image_base64}
 *   width={300}
 *   height={200}
 * />
 */

import React, { useState } from 'react';
import { View, Image, ActivityIndicator, Text, StyleSheet, Dimensions } from 'react-native';
import { colors, radius, spacing } from '../../theme/tokens';
import logger from '../../utils/logger';

interface GraphDisplayProps {
  imageBase64: string;
  title?: string;
  width?: number;
  height?: number;
  onLoad?: () => void;
  onError?: (error: string) => void;
}

/**
 * GraphDisplay - Renders base64-encoded graph images
 *
 * Displays mathematical function graphs generated by the backend.
 * Automatically handles loading states and errors gracefully.
 *
 * @param imageBase64 - Base64-encoded PNG image string (without data URI prefix)
 * @param title - Optional title to display above the graph
 * @param width - Image width in pixels (default: screen width - 40)
 * @param height - Image height in pixels (default: auto-calculated from width)
 * @param onLoad - Callback when image loads successfully
 * @param onError - Callback when image fails to load
 */
export default function GraphDisplay({
  imageBase64,
  title,
  width = Dimensions.get('window').width - 40,
  height,
  onLoad,
  onError
}: GraphDisplayProps) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [imageDimensions, setImageDimensions] = useState({
    width,
    height: height || width * 0.67 // Default 3:2 aspect ratio
  });

  // Construct data URI for Image component
  const imageUri = `data:image/png;base64,${imageBase64}`;

  const handleLoad = (event: any) => {
    setLoading(false);
    setError(false);

    // Get actual image dimensions if height not specified
    if (!height && event.nativeEvent?.source) {
      const { width: imgWidth, height: imgHeight } = event.nativeEvent.source;
      if (imgWidth && imgHeight) {
        // Calculate height maintaining aspect ratio
        const aspectRatio = imgHeight / imgWidth;
        const calculatedHeight = width * aspectRatio;
        setImageDimensions({
          width,
          height: calculatedHeight
        });
        logger.debug('Graph dimensions calculated', {
          originalWidth: imgWidth,
          originalHeight: imgHeight,
          displayWidth: width,
          displayHeight: calculatedHeight
        });
      }
    }

    onLoad?.();
    logger.info('Graph loaded successfully', {
      title,
      width: imageDimensions.width,
      height: imageDimensions.height
    });
  };

  const handleError = (e: any) => {
    setLoading(false);
    setError(true);
    const errorMsg = 'Failed to load graph image';
    onError?.(errorMsg);
    logger.error('Graph loading failed', {
      title,
      error: e?.nativeEvent?.error || 'Unknown error',
      base64Length: imageBase64?.length
    });
  };

  return (
    <View style={styles.container}>
      {title && (
        <View style={styles.titleContainer}>
          <Text style={styles.title}>{title}</Text>
        </View>
      )}

      <View style={[
        styles.graphContainer,
        { width: imageDimensions.width }
      ]}>
        {loading && (
          <View style={[
            styles.loadingContainer,
            {
              width: imageDimensions.width,
              height: imageDimensions.height
            }
          ]}>
            <ActivityIndicator
              size="large"
              color={colors.gold}
            />
            <Text style={styles.loadingText}>Loading graph...</Text>
          </View>
        )}

        {error ? (
          <View style={[
            styles.errorContainer,
            {
              width: imageDimensions.width,
              minHeight: 200
            }
          ]}>
            <Text style={styles.errorIcon}>📊</Text>
            <Text style={styles.errorText}>Failed to Load Graph</Text>
            <Text style={styles.errorDetail}>
              The graph image could not be displayed. Please try again.
            </Text>
          </View>
        ) : (
          <Image
            source={{ uri: imageUri }}
            style={{
              width: imageDimensions.width,
              height: imageDimensions.height
            }}
            resizeMode="contain"
            onLoad={handleLoad}
            onError={handleError}
            accessibilityLabel={title || 'Mathematical function graph'}
            accessibilityRole="image"
            accessibilityHint="Visual representation of a mathematical function"
          />
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    marginVertical: spacing[16],
  },
  titleContainer: {
    marginBottom: spacing[12],
    paddingHorizontal: spacing[16],
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    lineHeight: 22,
  },
  graphContainer: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 2,
    borderColor: colors.cardStroke,
    padding: spacing[12],
    overflow: 'hidden',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg2,
    borderRadius: radius.sm,
  },
  loadingText: {
    marginTop: spacing[12],
    fontSize: 14,
    color: colors.textDim,
  },
  errorContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.danger + '15', // 15% opacity
    borderRadius: radius.sm,
    padding: spacing[24],
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: spacing[12],
  },
  errorText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.danger,
    marginBottom: spacing[8],
    textAlign: 'center',
  },
  errorDetail: {
    fontSize: 14,
    color: colors.textDim,
    textAlign: 'center',
    lineHeight: 20,
  },
});
