import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  innerContainer: {
    flex: 1,
  },
  animatedContainer: {
    flex: 1,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 100,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#F8F4E3',
    marginBottom: 10,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#CBD5E0',
    textAlign: 'center',
    lineHeight: 22,
  },
  formContainer: {
    gap: 20,
  },
  inputContainer: {
    marginBottom: 4,
  },
  label: {
    color: '#F8F4E3',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(248, 244, 227, 0.1)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#F8F4E3',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  subjectInputWrapper: {
    position: 'relative',
  },
  clearSubjectInputButton: {
    position: 'absolute',
    right: 10,
    top: 12,
    padding: 4,
  },

  // Subject Selector Button Styles
  subjectSelectorButton: {
    backgroundColor: 'rgba(212, 175, 55, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 8,
  },
  subjectSelectorButtonActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    borderColor: '#D4AF37',
  },
  subjectSelectorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subjectSelectorText: {
    flex: 1,
    fontSize: 14,
    color: '#F8F4E3',
    marginLeft: 8,
    fontWeight: '500',
  },
  subjectSelectorTextActive: {
    color: '#D4AF37',
    fontWeight: '700',
  },
  selectedSubjectInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(40, 167, 69, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(40, 167, 69, 0.3)',
  },
  selectedSubjectText: {
    flex: 1,
    fontSize: 12,
    color: '#CBD5E0',
    marginLeft: 6,
  },
  clearSubjectButton: {
    padding: 4,
  },

  // Custom Dropdown Styles
  dropdownButton: {
    backgroundColor: 'rgba(248, 244, 227, 0.1)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dropdownContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownIcon: {
    marginRight: 12,
  },
  dropdownText: {
    flex: 1,
    fontSize: 16,
    color: '#F8F4E3',
  },
  dropdownPlaceholder: {
    color: '#CBD5E0',
    fontStyle: 'italic',
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: '#2C467D',
    borderRadius: 20,
    maxHeight: '70%',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(248, 244, 227, 0.1)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F8F4E3',
  },
  modalCloseButton: {
    padding: 5,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(248, 244, 227, 0.05)',
  },
  selectedOption: {
    backgroundColor: 'rgba(212, 175, 55, 0.1)',
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    color: '#F8F4E3',
    marginLeft: 12,
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    backgroundColor: 'rgba(248, 244, 227, 0.1)',
    borderRadius: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  slider: {
    flex: 1,
    height: 40,
    marginHorizontal: 16,
  },
  sliderThumb: {
    backgroundColor: '#D4AF37',
    width: 20,
    height: 20,
  },
  sliderLabel: {
    color: '#CBD5E0',
    fontSize: 14,
    fontWeight: '600',
    minWidth: 20,
    textAlign: 'center',
  },
  sliderHelper: {
    color: '#CBD5E0',
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  button: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginTop: 10,
  },
  buttonGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A2C5B',
    marginLeft: 8,
  },
  motivation: {
    fontSize: 14,
    color: '#CBD5E0',
    marginTop: 20,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 60,
    left: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(248, 244, 227, 0.1)',
    zIndex: 1,
  },
  backButtonText: {
    color: '#F8F4E3',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },

  // Freshness Indicator Styles
  freshnessIndicator: {
    position: 'absolute',
    top: 100,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#744210',
    borderColor: '#F6E05E',
    borderWidth: 1,
    borderRadius: 25,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
    gap: 8,
  },
  freshnessText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F6E05E',
  },
  quickSuggestions: {
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  quickSuggestionsLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#F8F4E3',
    marginBottom: 8,
  },
  quickSuggestionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickSuggestionChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
  },
  quickSuggestionText: {
    fontSize: 14,
    color: '#F8F4E3',
  },
  userCourseQuickChip: {
    borderWidth: 2,
    backgroundColor: 'rgba(212, 175, 55, 0.3)',
    borderColor: 'rgba(212, 175, 55, 0.6)',
    elevation: 2,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  detailsWindow: {
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  detailsLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#F8F4E3',
    marginBottom: 8,
  },
  detailsInput: {
    backgroundColor: 'rgba(248, 244, 227, 0.08)',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#F8F4E3',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.2)',
    minHeight: 60,
    textAlignVertical: 'top',
  },

  // Validation Styles
  inputError: {
    borderColor: '#dc3545',
    borderWidth: 2,
  },
  inputValid: {
    borderColor: '#28a745',
    borderWidth: 2,
  },
  inputValidationContainer: {
    marginTop: 8,
  },
  validationIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  validatingText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#D4AF37',
    fontWeight: '500',
  },
  validationSuccessText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#28a745',
    fontWeight: '600',
  },
  validationErrorText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#dc3545',
    fontWeight: '500',
    flex: 1,
  },

  // Hierarchical Course Selection Styles
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 8,
  },
  activeToggle: {
    backgroundColor: '#D4AF37',
  },
  toggleText: {
    fontSize: 14,
    fontWeight: '600',
  },
  hierarchicalStep: {
    marginBottom: 16,
  },
  stepLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#CBD5E0',
    marginBottom: 8,
  },
  selectionSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(40, 167, 69, 0.1)',
    borderColor: 'rgba(40, 167, 69, 0.3)',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  summaryText: {
    fontSize: 14,
    color: '#28a745',
    fontWeight: '600',
  },
  noCoursesMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(243, 156, 18, 0.1)',
    borderColor: 'rgba(243, 156, 18, 0.3)',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  noCoursesText: {
    fontSize: 12,
    color: '#F39C12',
    flex: 1,
    lineHeight: 16,
  },
});
