import { StyleSheet } from 'react-native';

// Base styles for ResultsScreen
export const styles = StyleSheet.create({
  container: { flex: 1 },
  centerContent: { justifyContent: 'center', alignItems: 'center' },
  errorText: { fontSize: 18, fontWeight: '600', marginBottom: 20, textAlign: 'center' },
  explanationErrorContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
  },
  explanationErrorText: {
    fontSize: 16,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  scrollContainer: { paddingHorizontal: 20, paddingTop: 60, paddingBottom: 40 },
  headerContainer: { marginBottom: 30 },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  titleSection: { alignItems: 'center', marginBottom: 30 },
  titleIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  title: { fontSize: 32, fontWeight: '800', marginBottom: 8, textAlign: 'center', letterSpacing: -0.5 },
  subtitle: { fontSize: 16, textAlign: 'center', lineHeight: 22, paddingHorizontal: 20 },
  scoreCard: {
    borderRadius: 20,
    padding: 24,
    marginBottom: 30,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
  },
  performanceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 20,
    gap: 8,
  },
  performanceText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  scoreDisplay: { alignItems: 'center', marginBottom: 24 },
  scoreNumber: { fontSize: 48, fontWeight: '900', marginBottom: 4, letterSpacing: -1 },
  scoreLabel: { fontSize: 16, opacity: 0.8 },
  statsRow: { flexDirection: 'row', alignItems: 'center', width: '100%', justifyContent: 'space-around', marginTop: 16 },
  statItem: { alignItems: 'center', flex: 1, gap: 8 },
  statNumber: { fontSize: 24, fontWeight: '700' },
  statLabel: { fontSize: 14, opacity: 0.7 },
  statDivider: { width: 1, height: 40, backgroundColor: 'rgba(0,0,0,0.1)', marginHorizontal: 20 },

  // New pill badge styles
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  statPillText: {
    fontSize: 14,
    fontWeight: '600',
  },

  // Progress bar styles
  progressBarContainer: {
    width: '100%',
    marginTop: 12,
  },
  progressBarBackground: {
    width: '100%',
    height: 6,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 3,
  },

  // Motivational message style
  motivationalMessage: {
    textAlign: 'center',
    fontStyle: 'italic',
  },

  // Enhanced visual styles for improved card
  scoreNumberLarge: {
    fontSize: 64,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: -2,
    marginBottom: 8,
  },
  scoreLabelLarge: {
    fontSize: 18,
    textAlign: 'center',
    opacity: 0.7,
    marginBottom: 20,
  },
  performanceBadgeEnhanced: {
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 25,
    marginBottom: 24,
    alignSelf: 'center',
  },
  inlineStatsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    gap: 32,
  },
  inlineStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statIcon: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  inlineStatText: {
    fontSize: 16,
    fontWeight: '600',
  },
  motivationalMessageLarge: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  analyticsStatsRowCompact: {
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    marginTop: 8,
  },
  analyticsCompactText: {
    fontSize: 12,
    opacity: 0.6,
    textAlign: 'center',
  },

  // Usage stats card styles
  usageCard: {
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  usageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  usageTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  usageProgress: {
    alignItems: 'center',
  },
  usageBar: {
    width: '100%',
    height: 6,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 3,
    marginBottom: 8,
  },
  usageBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  usageText: {
    fontSize: 14,
    opacity: 0.8,
  },

  questionsSection: { marginBottom: 30 },
  sectionTitle: { fontSize: 24, fontWeight: '700', marginBottom: 20, textAlign: 'center' },
  questionCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 2,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
  },
  questionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  questionNumber: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  questionNumberText: { fontSize: 16, fontWeight: '700' },
  resultIndicator: { width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  correctIndicator: { backgroundColor: '#28a745' },
  incorrectIndicator: { backgroundColor: '#dc3545' },
  questionText: { fontSize: 18, fontWeight: '600', lineHeight: 24, marginBottom: 16 },
  answerSection: { marginBottom: 12 },
  answerLabel: { fontSize: 14, fontWeight: '600', marginBottom: 4, opacity: 0.8 },
  userAnswer: { fontSize: 16, fontWeight: '600', paddingVertical: 2 },
  correctAnswer: { color: '#28a745' },
  incorrectAnswer: { color: '#dc3545' },
  strikeThrough: { textDecorationLine: 'line-through', opacity: 0.7 },
  correctAnswerDisplay: { fontSize: 16, fontWeight: '600', color: '#155724' },

  // Enhanced explanation styles
  explanationActions: {
    marginTop: 16,
  },
  explanationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 2,
    marginBottom: 12,
    gap: 8,
  },
  explanationButtonActive: {
    borderWidth: 3,
  },
  explanationButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  explanationPreview: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  explanationPreviewText: {
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 8,
  },
  viewFullButton: {
    alignSelf: 'flex-end',
  },
  viewFullButtonText: {
    fontSize: 12,
    fontWeight: '600',
  },

  // Modal styles
  explanationModal: {
    flex: 1,
  },
  explanationModalHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  modalTitleSection: {
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 8,
  },
  tierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  tierBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  modalQuestionText: {
    fontSize: 16,
    textAlign: 'center',
    opacity: 0.8,
  },
  explanationModalContent: {
    flex: 1,
    padding: 20,
  },
  explanationSection: {
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  sectionText: {
    fontSize: 14,
    lineHeight: 20,
  },
  stepItem: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  stepNumber: {
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
    minWidth: 20,
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  bulletPoint: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  aiInfoFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  aiInfoText: {
    fontSize: 12,
    textAlign: 'center',
    opacity: 0.7,
  },

  // Tier selection modal styles
  tierModal: {
    flex: 1,
  },
  tierModalHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    alignItems: 'center',
  },
  tierModalSubtitle: {
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.7,
    marginTop: 8,
  },
  tierOptions: {
    flex: 1,
    padding: 20,
  },
  tierOption: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 2,
  },
  tierOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  tierIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  tierInfo: {
    flex: 1,
  },
  tierName: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  tierModel: {
    fontSize: 14,
    opacity: 0.7,
  },
  tierCost: {
    alignItems: 'flex-end',
  },
  tierCostText: {
    fontSize: 16,
    fontWeight: '600',
  },
  tierLimit: {
    fontSize: 12,
    opacity: 0.7,
  },
  tierFeatures: {
    marginBottom: 12,
  },
  tierFeature: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  currentTierBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  currentTierText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },

  explanationContainer: { marginTop: 16, padding: 16, borderRadius: 12, borderWidth: 1 },
  explanationHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  explanationTitle: { fontSize: 16, fontWeight: '600' },
  explanationText: { fontSize: 14, lineHeight: 20 },
  solutionContainer: { marginTop: 16, padding: 16, borderRadius: 12, borderWidth: 1 },
  solutionTitle: { fontSize: 16, fontWeight: '600', marginBottom: 8 },
  solutionStep: { fontSize: 14, lineHeight: 20, marginBottom: 4 },
  actionContainer: { marginTop: 20, alignItems: 'center' },
  enhancedActionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16, width: '100%' },
  enhancedActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 12,
    marginHorizontal: 4,
    borderWidth: 2,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4
  },
  enhancedButtonText: { fontSize: 14, fontWeight: '600', marginLeft: 8 },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginVertical: 8,
    width: '100%',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4
  },
  primaryButton: { backgroundColor: '#1A2C5B' },
  secondaryButton: { backgroundColor: '#F8F9FA', borderWidth: 1, borderColor: '#1A2C5B' },
  buttonText: { fontSize: 16, fontWeight: '600', marginLeft: 8 },
  insightCard: {
    marginVertical: 20,
    padding: 20,
    borderRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
  },
  insightTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  insightText: {
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 8,
  },
  insightDetail: {
    fontSize: 14,
    opacity: 0.8,
    marginBottom: 16,
  },
  focusQuizButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 8,
  },
  focusQuizButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  actionButtonsContainer: { marginTop: 20, width: '100%', alignItems: 'center' },

  // AI-powered insights styles
  aiRecommendationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(212, 175, 55, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 8,
    gap: 8,
  },
  aiRecommendationText: {
    fontSize: 13,
    fontStyle: 'italic',
    flex: 1,
  },
  granularTopicsContainer: {
    marginTop: 8,
    marginBottom: 8,
  },
  granularTopicsLabel: {
    fontSize: 11,
    fontWeight: '500',
    marginBottom: 4,
    opacity: 0.7,
  },
  topicsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  topicTag: {
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  topicTagText: {
    fontSize: 10,
    fontWeight: '500',
  },

  // Clean AI Analysis Section Styles
  aiAnalysisSection: {
    marginHorizontal: 20,
    marginVertical: 20,
    backgroundColor: 'rgba(248, 249, 250, 0.8)',
    borderRadius: 16,
    padding: 20,
  },
  aiAnalysisTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  aiAnalysisSubtitle: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
    opacity: 0.7,
  },
  analysisCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  analysisHeader: {
    marginBottom: 12,
  },
  analysisQuestionText: {
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 16,
    fontWeight: '500',
  },
  answerComparison: {
    backgroundColor: 'rgba(248, 250, 252, 0.8)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  answerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  wrongLabel: {
    color: '#DC2626',
  },
  correctLabel: {
    color: '#059669',
  },
  answerValue: {
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  wrongAnswer: {
    color: '#DC2626',
    backgroundColor: 'rgba(220, 38, 38, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  correctAnswerText: {
    color: '#059669',
    backgroundColor: 'rgba(5, 150, 105, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  aiExplanationContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 8,
    padding: 16,
  },
  explanationBlock: {
    marginBottom: 16,
  },
  explanationLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  explanationContent: {
    fontSize: 14,
    lineHeight: 20,
    paddingLeft: 8,
  },
  tipItem: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 4,
    paddingLeft: 8,
  },
});

// Additional analytics styles
export const newAnalyticsStyles = {
  analyticsMessage: {
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 4,
    textAlign: 'center',
  },
  analyticsStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  analyticsStat: {
    alignItems: 'center',
  },
  analyticsStatLabel: {
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 4,
  },
  analyticsStatValue: {
    fontSize: 18,
    fontWeight: '700',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    fontStyle: 'italic',
  },
  profileStatsCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  profileTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  profileStatsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  profileStatItem: {
    alignItems: 'center',
  },
  profileStatValue: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  profileStatLabel: {
    fontSize: 12,
    fontWeight: '500',
    opacity: 0.8,
  },
  subjectProgress: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  subjectProgressTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  subjectProgressItem: {
    marginBottom: 12,
  },
  subjectName: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  progressBar: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 3,
  },
  progressPercentage: {
    fontSize: 12,
    fontWeight: '600',
    minWidth: 35,
    textAlign: 'right',
  },
};

// Light theme styles
export const lightStyles = StyleSheet.create({
  container: { backgroundColor: '#F8F9FA' },
  backButton: { backgroundColor: '#FFFFFF' },
  backButtonText: { color: '#1A2C5B' },
  titleIcon: { backgroundColor: 'rgba(26, 44, 91, 0.1)' },
  title: { color: '#1A2C5B' },
  subtitle: { color: '#4A5568' },
  scoreCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0' },
  scoreNumber: { color: '#1A2C5B' },
  scoreLabel: { color: '#4A5568' },
  statItem: { backgroundColor: '#F1F5F9' },
  statLabel: { color: '#4A5568' },
  sectionTitle: { color: '#1A2C5B' },
  questionCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0' },
  correctCard: { borderColor: '#28a745' },
  incorrectCard: { borderColor: '#dc3545' },
  questionNumber: { backgroundColor: '#E2E8F0' },
  correctNumber: { backgroundColor: '#28a745' },
  incorrectNumber: { backgroundColor: '#dc3545' },
  questionNumberText: { color: '#1A2C5B' },
  correctNumberText: { color: '#FFFFFF' },
  incorrectNumberText: { color: '#FFFFFF' },
  questionText: { color: '#2D3748' },
  answerLabel: { color: '#4A5568' },
  correctAnswerDisplay: { color: '#155724' },
  explanationContainer: { backgroundColor: '#F8F9FA', borderColor: '#E2E8F0' },
  explanationIcon: { color: '#D4AF37' },
  explanationTitle: { color: '#1A2C5B' },
  explanationText: { color: '#4A5568' },
  solutionContainer: { backgroundColor: '#F8F9FA', borderColor: '#E2E8F0' },
  solutionTitle: { color: '#1A2C5B' },
  solutionStep: { color: '#4A5568' },
  explanationButton: { backgroundColor: '#FFF3CD', borderColor: '#D4AF37' },
  explanationButtonText: { color: '#D4AF37' },
  saveQuizButton: { backgroundColor: '#E2E8F0', borderColor: '#1A2C5B' },
  saveQuizButtonText: { color: '#1A2C5B' },
  shareButton: { backgroundColor: 'rgba(23, 162, 184, 0.1)', borderColor: '#17a2b8' },
  shareButtonText: { color: '#17a2b8' },
  copyButton: { backgroundColor: 'rgba(40, 167, 69, 0.1)', borderColor: '#28a745' },
  copyButtonText: { color: '#28a745' },
  primaryButton: { backgroundColor: '#1A2C5B' },
  primaryButtonText: { color: '#FFFFFF' },
  secondaryButton: { backgroundColor: '#F8F9FA', borderColor: '#1A2C5B' },
  secondaryButtonText: { color: '#1A2C5B' },
  insightCard: { backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#F6E05E' },
  insightTitle: { color: '#975A16' },
  insightText: { color: '#4A5568' },
  insightDetail: { color: '#718096' },
  focusQuizButton: { backgroundColor: '#D4AF37' },
  focusQuizButtonText: { color: '#1A2C5B' },
  refreshColor: { color: '#1A2C5B' },
  aiRecommendationBox: { backgroundColor: 'rgba(212, 175, 55, 0.1)' },
  aiRecommendationText: { color: '#4A5568' },
  granularTopicsLabel: { color: '#718096' },
  topicTag: { backgroundColor: 'rgba(212, 175, 55, 0.15)', borderColor: 'rgba(212, 175, 55, 0.3)' },
  topicTagText: { color: '#975A16' },
  modalContainer: { backgroundColor: '#FFFFFF' },
  modalTitle: { color: '#1F2937' },
  modalText: { color: '#6B7280' },
  optionButton: { backgroundColor: '#F9FAFB', borderColor: '#E5E7EB' },
  optionText: { color: '#1F2937' },
  inputContainer: { backgroundColor: '#FFFFFF' },
  textInput: { backgroundColor: '#F9FAFB', color: '#1F2937', borderColor: '#E5E7EB' },
  placeholderText: { color: '#9CA3AF' },
  cancelButton: { backgroundColor: '#F9FAFB', borderColor: '#E5E7EB' },
  cancelButtonText: { color: '#6B7280' },
  submitButton: { backgroundColor: '#10B981' },
  submitButtonText: { color: '#FFFFFF' },
});

// Dark theme styles
export const darkStyles = StyleSheet.create({
  container: { backgroundColor: '#1A202C' },
  backButton: { backgroundColor: '#2D3748' },
  backButtonText: { color: '#E2E8F0' },
  titleIcon: { backgroundColor: 'rgba(212, 175, 55, 0.2)' },
  title: { color: '#E2E8F0' },
  subtitle: { color: '#A0AEC0' },
  scoreCard: { backgroundColor: '#2D3748', borderColor: '#4A5568' },
  scoreNumber: { color: '#E2E8F0' },
  scoreLabel: { color: '#A0AEC0' },
  statItem: { backgroundColor: '#4A5568' },
  statLabel: { color: '#A0AEC0' },
  sectionTitle: { color: '#E2E8F0' },
  questionCard: { backgroundColor: '#2D3748', borderColor: '#4A5568' },
  correctCard: { borderColor: '#28a745' },
  incorrectCard: { borderColor: '#dc3545' },
  questionNumber: { backgroundColor: '#4A5568', color: '#60A5FA' },
  correctNumber: { backgroundColor: '#28a745' },
  incorrectNumber: { backgroundColor: '#dc3545' },
  questionNumberText: { color: '#E2E8F0' },
  correctNumberText: { color: '#FFFFFF' },
  incorrectNumberText: { color: '#FFFFFF' },
  questionText: { color: '#E2E8F0' },
  answerLabel: { color: '#A0AEC0' },
  correctAnswerDisplay: { color: '#9AE6B4' },
  explanationContainer: { backgroundColor: '#4A5568', borderColor: '#718096' },
  explanationIcon: { color: '#F6E05E' },
  explanationTitle: { color: '#E2E8F0' },
  explanationText: { color: '#A0AEC0' },
  solutionContainer: { backgroundColor: '#4A5568', borderColor: '#718096' },
  solutionTitle: { color: '#E2E8F0' },
  solutionStep: { color: '#A0AEC0' },
  explanationButton: { backgroundColor: '#744210', borderColor: '#F6E05E' },
  explanationButtonText: { color: '#F6E05E' },
  saveQuizButton: { backgroundColor: '#4A5568', borderColor: '#E2E8F0' },
  saveQuizButtonText: { color: '#E2E8F0' },
  shareButton: { backgroundColor: 'rgba(23, 162, 184, 0.2)', borderColor: '#17a2b8' },
  shareButtonText: { color: '#17a2b8' },
  copyButton: { backgroundColor: 'rgba(40, 167, 69, 0.2)', borderColor: '#28a745' },
  copyButtonText: { color: '#28a745' },
  primaryButton: { backgroundColor: '#4A5568' },
  primaryButtonText: { color: '#E2E8F0' },
  secondaryButton: { backgroundColor: '#2D3748', borderColor: '#E2E8F0' },
  secondaryButtonText: { color: '#E2E8F0' },
  insightCard: { backgroundColor: '#422C0A', borderWidth: 1, borderColor: '#F6E05E' },
  insightTitle: { color: '#F6E05E' },
  insightText: { color: '#E2E8F0' },
  insightDetail: { color: '#A0AEC0' },
  focusQuizButton: { backgroundColor: '#F6E05E' },
  focusQuizButtonText: { color: '#1A202C' },
  refreshColor: { color: '#F6E05E' },
  aiRecommendationBox: { backgroundColor: 'rgba(212, 175, 55, 0.2)' },
  aiRecommendationText: { color: '#E2E8F0' },
  granularTopicsLabel: { color: '#A0AEC0' },
  topicTag: { backgroundColor: 'rgba(212, 175, 55, 0.25)', borderColor: 'rgba(212, 175, 55, 0.4)' },
  topicTagText: { color: '#F6E05E' },
  aiAnalysisSection: { backgroundColor: 'rgba(45, 55, 72, 0.9)' },
  aiAnalysisTitle: { color: '#E2E8F0' },
  aiAnalysisSubtitle: { color: '#A0AEC0' },
  analysisCard: { backgroundColor: '#2D3748', borderColor: '#4A5568' },
  analysisQuestionText: { color: '#E2E8F0' },
  answerComparison: { backgroundColor: 'rgba(74, 85, 104, 0.5)' },
  wrongLabel: { color: '#F87171' },
  correctLabel: { color: '#34D399' },
  wrongAnswer: { color: '#F87171', backgroundColor: 'rgba(248, 113, 113, 0.2)' },
  correctAnswerText: { color: '#34D399', backgroundColor: 'rgba(52, 211, 153, 0.2)' },
  aiExplanationContainer: { backgroundColor: 'rgba(45, 55, 72, 0.7)' },
  explanationLabel: { color: '#E2E8F0' },
  explanationContent: { color: '#CBD5E0' },
  tipItem: { color: '#A0AEC0' },
  modalContainer: { backgroundColor: '#2D3748' },
  modalTitle: { color: '#E2E8F0' },
  modalText: { color: '#A0AEC0' },
  optionButton: { backgroundColor: '#4A5568', borderColor: '#718096' },
  optionText: { color: '#E2E8F0' },
  inputContainer: { backgroundColor: '#2D3748' },
  textInput: { backgroundColor: '#4A5568', color: '#E2E8F0', borderColor: '#718096' },
  placeholderText: { color: '#6B7280' },
  cancelButton: { backgroundColor: '#4A5568', borderColor: '#718096' },
  cancelButtonText: { color: '#E2E8F0' },
  submitButton: { backgroundColor: '#065F46' },
  submitButtonText: { color: '#FFFFFF' },
});
